apiVersion: v1
kind: ServiceAccount
metadata:
  name: genreflow-backend
  namespace: genreflow-backend
  labels:
    app.kubernetes.io/name: genreflow
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: genreflow
automountServiceAccountToken: false
