apiVersion: v1
kind: ServiceAccount
metadata:
  name: genreflow-frontend
  namespace: genreflow-frontend
  labels:
    app.kubernetes.io/name: genreflow
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: genreflow
automountServiceAccountToken: false
