apiVersion: v1
kind: Service
metadata:
  name: genreflow-frontend
  namespace: genreflow-frontend
  labels:
    app.kubernetes.io/name: genreflow
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: genreflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: genreflow
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: 80
      targetPort: http
