---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: genreflow-frontend
spec:
  encryptedData:
    .dockerconfigjson: AgCOwT9YBSyujw62kkJWbVhEnxIZ0RvVAaO1mumTmQsw5B7G5uQTcXMQ9EpMpbj1rP2SdbsUw3MPcHhcKKa+7PgfwrRX8NS6jM+eJFgjBaoGU5c5gWNcLGLDFhOqiIl4vte6XSYksuq6UFgc/+XKfhVK67esQhgQ4CKc4UoJfEl9wt2qf5TTqXR42QNngF6qT5S7EMZSS7fIxEFacYhUiIzJqz2EM65u1l6dJTFmI5fGkwiaJs5aK4XQbLQk8o2E0ewXx8jtFWUCDzMuTLWM4kUVhadnsYOkHJIy2w+SmUs4/FTMKK4aLFjOTZ3UYIaa1zHv7B3o0NtcjFV7cpVUlKu/QmjD5JeJk9KP6QT702CBk9kwaDBtoJdXHMkXotaTw6l+3yRrHdLIOSxVuNOKEwDNmRK+Bip6RmXa2wOBDyEsshxLjhFc8zYUP8I262nfc6ZuHz3ppWvJ0vwhxLTYfK3SsZ5EHzc7jAUNivYoqJOIyYbRpfaGcvMiX9tgpFw2b9tpm/ZLr71Eh2/XKm4m+Y6BMnE/HO2S1uneXghieLY/J038zEQbd1rOjOhtw6X4OmTDHtXh14vAw25bmEwSojB0BMysfYYwr6EKNapJ62XXuKyBEQwwbTOJoNvdi/d9odYtONEF/WifROCwVv4oIi+YehPVfMuh0uOqGS3rniSSKFKUycxyCTPa5gKd1MpIONnlYdK90ipx/XJBJZnKpKuv02JqXM+cC3kYwF5KqHd/5xv1+PiszvTeid0ZFL3tZ87wqco7W3hHuXiM4SX+wb5uWhbfRvMvdRUFV5VvK15SnV5TMzM83HHnX3rr7n4tkPiVUmtuRrOylVd8REyEzEIXn87x3/GnFryzziIENMlJPlWy0wkTZm//wD8LbOiKhOgH/xf1woJi4keX2pz/+5PaVKcxvpi8b/SXs6KQ4ZSHuv3IJoWvvfw7tzMiiTLBMRnZX4Absbv+v/80uLwkA6bhCkI1c4ndsdx9TlwXASY=
  template:
    metadata:
      name: dockerhub-secret
      namespace: genreflow-frontend
    type: kubernetes.io/dockerconfigjson
