---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: genreflow-backend
spec:
  encryptedData:
    .dockerconfigjson: AgBHEHQviVNS5KgXqXMTq7iT27qD8Z/W4tTIMloHkfLPMXAArpcU7i/0jMuXzBVG8pH4VKdYXIUQMD+GVFP0FHUftyEoxcAq5G+QCXv65kd4ENj1vGfp7glMZkSu0hSm9OcGGhnPAG/2chdStZ79dU5v6gJ4m1g/jZrGZJN/uw81EspjNfP/gC9fVp5Wm0oXS4qJx4tFmHUdzF63Yp4QeOf674e0vmzwmKhCBGqAczjDE7vnbdzdNeoIl8yVYyeaKTBFYbHMXuky64E/km90hroWdqOboXWCOXcdQNwx0KEI8h6BF7628LgEzqvpYnZ9XnqrcJu/6oR6rrFaA+zGVNOh4Wew5fDRMOZoMMDruXDBlhDgSgM3Wc0kc7ZLse2LDARgevkO1q+PQ75XymRKADQe2EURO5ntMeO5couXB2Hz5eUvnURs2kxIhYN3qsEcPb46SHWXtkgIiDp9VB6mUAZWwxCfkFi74UIqAqnMifikwlDU6qxf7m++vJuo7CjQSfKLevk11dikYEDBlNOyEP9WXVTNoRAswfA6rFF2z5ss2bAhifB5dN90dnWMKEPD4JwVEMtyFSLxPMIUtH/uFIWzcL62elx/hqr0RlPSpWgeni7piPoLU3QXxBuNuIkUJmUuh2YH4VvwK1eAosoopwUzFFZPkKvrR96aP7DwewMNLJKG12M18LLMvUP64sb6kWxRcFGjfuwsB9LXF+1ibAVElCrTr8EOWT23PhOPulWIMVLA7gT3/lvoUIiHc4yCTvqUlgNFUnYE0hNTBhGJ1eksI5XS7IqdP1JaDfa4xckSttmdBhKOtv2z4qjz5cgZvE2EkvlbMi8/vBx6HRzPJx6vN5+U47JwG+TnC6m9odECUYIz/Df8KkMUm5XC+NviMRYFmDxfxNDqaBfbhqm+iBJD0F+kOIJTAsMw1l4JnkyUKYYWpIALUhXTK53HRigIBkqKgRO02fepeiVFSwBS8MD+WeNvWu2r3qOPYbPyofs=
  template:
    metadata:
      name: dockerhub-secret
      namespace: genreflow-backend
    type: kubernetes.io/dockerconfigjson
